name: startpro_zahra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Check if a newer version exists
  file_picker: ^9.2.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/naqel_logo.png
    - assets/zajil_logo.png
    - assets/dhl_logo.png
    - assets/fedex_logo.png
    - assets/default_logo.png
    - assets/salla_logo.png
    - assets/zid_logo.png
    - assets/shopify_logo.png
    - assets/woocommerce_logo.png

dependency_overrides:
  material_color_utilities: ^0.12.0
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

  
